brew "age"
brew "antidote"
brew "chezmoi"
brew "fzf"
brew "go-task"
brew "python"
brew "ripgrep"
brew "starship"
brew "zoxide"

cask "chatgpt"
cask "codex"
cask "font-maple-mono-nf-cn"
cask "ghostty"
cask "visual-studio-code"
