#!/usr/bin/env zsh

##################################
# command -v zsh | sudo tee -a /etc/shells
# chsh -s "$(command -v zsh)"
##################################

[[ -f $HOME/.config/zsh/init.zsh ]] && source $HOME/.config/zsh/init.zsh
