#!/usr/bin/env zsh

##################################
# sudo cat /etc/shells | grep "$(command -v zsh)" || sudo echo "$(command -v zsh)" | sudo tee -a /etc/shells
# chsh -s "$(command -v zsh)"
##################################

[[ -f $HOME/.config/zsh/init.zsh ]] && source $HOME/.config/zsh/init.zsh
