[[packages.darwin.pkgManager]]
cmd = "brew"
name = "Homebrew"
install_script = """
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
"""

[packages.darwin.brews]
commands = [
  { cmd = "gcc"         , name = "gcc"      },
  { cmd = "zsh"         , name = "zsh"      },
  { cmd = "git"         , name = "git"      },
  { cmd = "curl"        , name = "curl"     },
  { cmd = "chezmoi"     , name = "chezmoi"  },
  { cmd = "nvim"        , name = "neovim"   },
  { cmd = "bat"         , name = "bat"      },
  { cmd = "jq"          , name = "jq"       },
  { cmd = "yq"          , name = "yq"       },
  { cmd = "eza"         , name = "eza"      },
  { cmd = "rg"          , name = "ripgrep"  },
  { cmd = "fd"          , name = "fd"       },
  { cmd = "fzf"         , name = "fzf"      },
  { cmd = "gitui"       , name = "gitui"    },
  { cmd = "file"        , name = "file"     },
  { cmd = "kcat"        , name = "kcat"     },
  { cmd = "starship"    , name = "starship" },
]
fonts = [
  { font = "FiraCode Nerd Font Mono", name = "font-fira-code-nerd-font" },
]
casks = [
  { aliases = [ "wezterm", "wezterm-nightly" ], name = "wezterm" },
]

[packages.windows.scoop]
buckets = [
  { name = "extras"                 , url = "extras"                                    },
  { name = "nerd-fonts"             , url = "nerd-fonts"                                },
  { name = "tlipoca9_scoop-buckets" , url = "https://github.com/tlipoca9/scoop-bucket"  },
]
commands = [
  { cmd = "git"      , name = "main/git"                   },
  { cmd = "innounp"  , name = "main/innounp"               },
  { cmd = "sudo"     , name = "main/sudo"                  },
  { cmd = "7z"       , name = "main/7zip"                  },
  { cmd = "dark"     , name = "main/dark"                  },
  { cmd = "curl"     , name = "main/curl"                  },
  { cmd = "chezmoi"  , name = "main/chezmoi"               },
  { cmd = "nvim"     , name = "main/neovim"                },
  { cmd = "make"     , name = "main/make"                  },
  { cmd = "rg"       , name = "main/ripgrep"               },
  { cmd = "gcc"      , name = "main/mingw"                 },
  { cmd = "jq"       , name = "main/jq"                    },
  { cmd = "gitui"    , name = "main/gitui"                 },
  { cmd = "fd"       , name = "main/fd"                    },
  { cmd = "eza"      , name = "main/eza"                   },
  { cmd = "bat"      , name = "main/bat"                   },
  { cmd = "starship" , name = "main/starship"              },
  { cmd = "fzf"      , name = "main/fzf"                   },
  { cmd = "wezterm"  , name = "extras/wezterm"             },
  { cmd = "zsh"      , name = "tlipoca9_scoop-bucket/zsh"  },
]
fonts = [
  { font = "FiraCode Nerd Font Mono", name = "nerd-fonts/FiraCode-NF" },
]

