[[packages.darwin.pkgManager]]
cmd = "brew"
name = "Homebrew"
install_script = """
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
"""

[packages.darwin.brews]
commands = [
  { cmd = "gcc"     , name = "gcc"      , desc = ""},
  { cmd = "zsh"     , name = "zsh"      , desc = ""},
  { cmd = "git"     , name = "git"      , desc = ""},
  { cmd = "curl"    , name = "curl"     , desc = ""},
  { cmd = "chezmoi" , name = "chezmoi"  , desc = ""},
  { cmd = "nvim"    , name = "neovim"   , desc = ""},
  { cmd = "bat"     , name = "bat"      , desc = ""},
  { cmd = "jq"      , name = "jq"       , desc = ""},
  { cmd = "yq"      , name = "yq"       , desc = ""},
  { cmd = "eza"     , name = "eza"      , desc = ""},
  { cmd = "rg"      , name = "ripgrep"  , desc = ""},
  { cmd = "fd"      , name = "fd"       , desc = ""},
  { cmd = "fzf"     , name = "fzf"      , desc = ""},
  { cmd = "gitui"   , name = "gitui"    , desc = ""},
  { cmd = "file"    , name = "file"     , desc = ""},
  { cmd = "kcat"    , name = "kcat"     , desc = ""},
]
fonts = [
  { font = "FiraCode Nerd Font Mono", name = "font-fira-code-nerd-font" },
]
casks = [
  { aliases = [ "wezterm", "wezterm-nightly" ], name = "wezterm" },
]

[packages.windows.scoop]
buckets = [
  { name = "extras",                  url = "extras"                                    },
  { name = "nerd-fonts",              url = "nerd-fonts"                                },
  { name = "tlipoca9-scoop-buckets",  url = "https://github.com/tlipoca9/scoop-bucket"  },
]
commands = [
  { cmd = "git",      name = "main/git"                   },
  { cmd = "sudo",     name = "main/sudo"                  },
  { cmd = "7zip",     name = "main/7zip"                  },
  { cmd = "dark",     name = "main/dark"                  },
  { cmd = "curl",     name = "main/curl"                  },
  { cmd = "chezmoi",  name = "main/chezmoi"               },
  { cmd = "nvim",     name = "main/neovim"                },
  { cmd = "make",     name = "main/make"                  },
  { cmd = "rg",       name = "main/ripgrep"               },
  { cmd = "zsh",      name = "tlipoca9-scoop-bucket/zsh"  },
]
fonts = [
  { font = "FiraCode Nerd Font Mono", name = "nerd-fonts/FiraCode-NF" },
]