[services.linux.docker]
enabled = true
[[services.linux.docker.osRelease]]
addUserToGroup = true
osReleaseId = "opencloudos"
checker = """
command -v docker >/dev/null 2>&1
"""
installer = """
sudo yum install docker -y
sudo systemctl enable docker
sudo systemctl start docker
"""

[services.linux.v2rayA]
enabled = true
[[services.linux.v2rayA.osRelease]]
osReleaseId = "opencloudos"
checker = """
docker ps | grep v2raya
"""
installer = """
if [ -f $HOME/.services/v2rayA/docker-compose.yml ]; then
  docker-compose -f $HOME/.services/v2rayA/docker-compose.yml up -d
fi
"""