[services.linux.docker]
enabled = true
[[services.linux.docker.osRelease]]
addUserToGroup = true
osReleaseId = "opencloudos"
checker = """
command -v docker >/dev/null 2>&1
"""
installer = """
sudo yum install docker -y
sudo systemctl enable docker
sudo systemctl start docker
"""
